Improve errors with SCSS
jackdomleo7/Checka11y.css pull request #31
Opened 2020-09-30 23:34 UTC by jackdomleo7

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Branched from #26 and requesting merge back into #26.

Implemented SCSS to allow for easier maintaining:
- Installed `stylelint-scss` for SCSS linting
- Separated each feature into it's own sub file
- Udated README & CONTRIBUTING
- Moved projects logos into their own logo directory
- Created minified version of the stylesheet
- Added npm scripts
- Installed `postcss-cli`, `autoprefixer` and `cssnano`

## Link(s)

- https://www.npmjs.com/package/stylelint-scss

## Screenshot(s)

![image](https://user-images.githubusercontent.com/43371432/94750224-7bef2e80-037d-11eb-936f-d61bbcbe4d1d.png)

## Checklist:

- [x] I have thoroughly read the [CONTRIBUTING](../CONTRIBUTING.md) guidelines.
- [x] I understand my pull request will be thoroughly reviewed at high detail.
- [x] I understand the work in my pull request will **only** be available in the next version release of Checka11y.css and not in the current version release.
- [x] I confirm the work in this pull request is valid according to my findings and is not something for anything personal.
- [x] I have updated the [README](../README.md) where and if applicable (still put an `x` if you have considered this but thought there was nothing to add or modify).
- [x] I have added myself to the `contributors` section in `package.json` (still put an `x` if you have considered this but decided not to add yourself).
- [x] I have checked I have **not** committed any **accidental** files.
- [x] I have tested all the main modern browsers (I.e. Chrome, Firefox, Edge, Safari - please leave this unchecked if there were any browsers listed you could not test and list them in the [help](#help) section with details why you couldn't test that browser)
- [x] All new and existing a11y checks still work correctly (compare your local `test/index.html` to the `test/index.html` in the `master` branch).

## Help

Couldn't install v10.x.x of Autoprefixer because it's not compatible with v8 of PostCSS, so had to downgrade to v9.8.6 of Autoprefixer, until they release a fix.

2020-10-01 09:58 UTC, jackdomleo7 commented
TODO: Remove styling from the component itself and only apply it to the error message.

@danspratling What's your recommendation with errors on void elements such as `<img />`?

2020-10-01 09:59 UTC, danspratling commented
> @danspratling What's your recommendation with errors on void elements such as <img />?

What do you mean?

2020-10-01 10:06 UTC, jackdomleo7 commented
> @danspratling What's your recommendation with errors on void elements such as ?
> 
> What do you mean?

We can't put an error message on an `<img />`, since you can't use `::after` or `::before` on it. You mentioned to me it's probably not a good idea putting the error styling (border/background/color/etc) on the component itself as it could conflict with already existing styles. Maybe that's not a better explanation 😅

2020-10-01 10:11 UTC, danspratling commented
Wouldn't that get solved by #35 anyway though? I would say it's a moot point given we already have an issue related to it.

2020-10-01 10:49 UTC, jackdomleo7 commented
I'm not explaining it well 😅

![image](https://user-images.githubusercontent.com/43371432/94800120-0d8d8900-03dc-11eb-801d-c1c3406f2e06.png)

On Twitter, you said the error styling should only go on the content error and not the component itself.

Nevermind, we can change it later if needed 😉

2020-10-01 11:04 UTC, danspratling commented
Yeah, so in the above the ERROR text should have a border. This is fine.
<img width="642" src="https://user-images.githubusercontent.com/11349104/94801464-fbace580-03dd-11eb-9c94-a14159e61187.png">

But this is a bit much with the error wrapping around the content too, so it should probably be removed, because we can't guarantee that this content won't be styled and therefore other styling may accidentally overwrite this anyway (or just be mistaken as content styling).
<img src="https://user-images.githubusercontent.com/43371432/94800120-0d8d8900-03dc-11eb-801d-c1c3406f2e06.png" alt="">

2020-10-01 11:13 UTC, danspratling requested changes
A couple of changes. I primarily want to add a "how to add a new error" to the readme to make it super clear without having to dig into files to figure it out.

2020-10-01 11:13 UTC, danspratling commented on src/_customisation.scss
> +    * Colors are broken down into RGB and A variables to be combined for the main color
This line can be removed. I was just playing with an idea but we didn't need it.

2020-10-01 11:13 UTC, danspratling commented on src/_base.scss
> +  * To use in SCSS with the @extend & @include command.
Can we document this in readme too, just so it's super clear how you'd use this?

2020-10-01 11:13 UTC, danspratling commented on src/features/_links.scss
> +      @include contentMessage(error, "Ensure that <audio> with controls attribute is not a child of <a> as it is an invalid HTML.");
These are SO MUCH CLEARER 👏
Love it when the comments can be entirely removed because they just aren't needed any more.

2020-10-01 14:31 UTC, danspratling approved these changes
There's nothing to review ... so ... looks fine to me! 👍

2020-10-01 14:45 UTC, jackdomleo7 commented
I was just updating both branches with `master`. I'll do the other changes tonight, then we'll see if it's worth merging sooner or later. I'd rather it not mess around or confuse the Hacktoberfesters. 🙂

2020-10-03 23:49 UTC, jackdomleo7 commented
Hi @danspratling. I have:
- Merged `master`
- Added recently merged features to SCSS
- Resolved above comments
- Raised #52 for another day

😊

2020-10-05 20:25 UTC, danspratling approved these changes
Looking good!

2020-10-05 20:26 UTC, merged